### ISSUE TITLE
Docker image build script

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#262]
Some cities might find it useful to be able to create a docker image for running uReport.  Well, it would need to be a collection of docker containers, probably marshalled using docker compose.

**Comment by inghamn** [comment]
@milovanderlinden  did some preliminary work on a Docker build

https://github.com/CodeForEindhoven/uReport

**Comment by milovanderlinden** [comment]
Exactly. We use rancher open source which I can highly recommend (www.rancher.com).

Part of the rancher config (yml) below; the external_links section points to the docker images for solr and mysql which are grouped (in our case) In an Data Environment.

```yaml
  environment:
    ADMINISTRATOR_EMAIL: admin@yourserver
    ADMINISTRATOR_NAME: John Doe
    ALLOW_OVERRIDE: 'true'
    APPLICATION_NAME: yourUreportInstanceName
    DB_HOST: docker_mysql
    DB_NAME: open311_db
    DB_PASS: topsecret
    DB_USER: root
    DEFAULT_CITY: Bloomington
    DEFAULT_STATE: Indiana
    LOCALE: nl_EN
    LOCATION_NAME: Bloomington
    OPEN311_JURISDICTION: bloomington.in.gov
    OPEN311_KEY_SERVICE: https://yourserver/open311-api-key-request
    SOLR_CORE: open311_solr
    SOLR_SERVER_HOSTNAME: docker_solr
    SOLR_SERVER_PATH: /solr/open311_solr
    APPLICATION_THEME: yourtheme
  external_links:
  - 'Data/docker_mysql:'
  - 'Data/docker_solr:'
```

**Comment by milovanderlinden** [comment]
Important addition for rancher: 

Our docker image for uReport is available at hub.docker.com https://hub.docker.com/r/codefornl/ureport-docker/

You should have an volume for the media (images) that users can upload otherwise the media will be deleted everytime you refresh the docker image.

```yaml
image: codefornl/ureport-docker:stable
  volumes:
  - open311media:/webdir/crm/data/media
  volume_driver: convoy-gluster
```
